language: perl

perl:
  - "5.16"

branches:
  only:
      - master

before_install:
  - cpanm Carton

install:
  - 'carton install --deployment'

before_script:
  - carton exec daiku setup

script:
  - carton exec riji publish
